#!/usr/bin/env bash
# =============================================================================
# GLM-4.5-Air KTransformers REAL Full Fine-Tuning (FFT) Test Script
#
# Purpose:
#   Measure full-FT GPU VRAM and host RAM behavior for GLM-4.5-Air with
#   KTransformers AMXBF16 expert execution and 4-GPU FSDP sharding for
#   GPU-resident non-expert weights.
#
# Main outputs:
#   - monitor.csv / plots: runtime GPU VRAM, CPU RAM and utilization timeline
#   - memory_breakdown_estimate.txt: static attribution by params/grads/optimizer
#   - observed_memory_breakdown.txt: observed peak by phase from monitor.csv
#   - phase4_analysis.txt: TPS after excluding warm-up steps
#
# Dataset:
#   FFTtest/dataset/fft_real_100.json, generated by FFTtest/dataset/gen_dataset.py
#
# Usage:
#   bash run_full_ft_test_1gpu_bf16.sh [--skip-phase4] [--only-phase4] \
#        [--gpu 0] [--gpu-ids 0,1,2,3] [--phase4-steps 15] [--dry-run]
#
# Important:
#   ACCELERATE_KT_TRAIN_MODE=full is required. finetuning_type=full alone is not
#   sufficient for KT expert full-weight gradients.
# =============================================================================

set -euo pipefail

export ACCELERATE_KT_TRAIN_MODE=full

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_BASE="${SCRIPT_DIR}/test_log"
CONFIGS_DIR="${SCRIPT_DIR}/configs"
DATA_DIR="/mnt/data2/wbw/FFTtest/dataset"
DATASET_NAME="fft_real_100"
GEN_DATASET_SCRIPT="${DATA_DIR}/gen_dataset.py"
MONITOR_SCRIPT="${SCRIPT_DIR}/monitor.py"
ANALYZE_SCRIPT="${SCRIPT_DIR}/analyze.py"

LLAMA_FACTORY_DIR="/mnt/data2/wbw/LLaMA-Factory"
MODEL_PATH="/mnt/data3/models/GLM-4.5-Air"

ACCEL_CONFIG="${CONFIGS_DIR}/accelerate_fft_amxbf16_4gpu.yaml"
TRAIN_CONFIG_BASE="${CONFIGS_DIR}/train_full_ft_glm45_air.yaml"

CUTOFF_LEN=1024
WARMUP_SKIP="${WARMUP_SKIP:-5}"
PHASE4_STEPS=15
GPU_START=0
NUM_GPUS=4
GPU_IDS="${GPU_IDS:-}"
DRY_RUN=0
KEEP_MODEL_OUTPUT="${KEEP_MODEL_OUTPUT:-0}"
BACKEND_LABEL="AMX_BF16_FULLFT"

MONITOR_FIFO="/tmp/glm45_air_fft_monitor_events.fifo"
MONITOR_PID=""

CONDA_ENV="${FFT_CONDA_ENV:-Kllama}"

_find_conda_python() {
    local env="$1"
    local candidates=(
        "/mnt/data2/wbw/conda/envs/${env}/bin/python3"
        "/mnt/data2/wbw/miniconda3/envs/${env}/bin/python3"
        "/opt/conda/envs/${env}/bin/python3"
        "$(conda run -n "${env}" which python3 2>/dev/null || true)"
    )
    for p in "${candidates[@]}"; do
        [[ -x "${p}" ]] && { echo "${p}"; return 0; }
    done
    echo "python3"
}
PYTHON="$(_find_conda_python "${CONDA_ENV}")"
CONDA_BIN_DIR="$(dirname "${PYTHON}")"

make_gpu_ids() {
    local start="$1"
    local count="$2"
    local ids=()
    local i
    for ((i = 0; i < count; i++)); do
        ids+=("$((start + i))")
    done
    local IFS=,
    echo "${ids[*]}"
}

count_gpu_ids() {
    local ids="$1"
    local item count=0
    for item in ${ids//,/ }; do
        [[ -n "${item}" ]] && count=$((count + 1))
    done
    echo "${count}"
}

SKIP_PHASE4=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --skip-phase4) SKIP_PHASE4=1 ;;
        --only-phase4) ;;
        --phase4-steps) PHASE4_STEPS="$2"; shift ;;
        --gpu) GPU_START="$2"; GPU_IDS=""; shift ;;
        --gpu-ids) GPU_IDS="$2"; shift ;;
        --gpus)
            NUM_GPUS="$2"; shift
            if [[ ! "${NUM_GPUS}" =~ ^[0-9]+$ || "${NUM_GPUS}" -ne 4 ]]; then
                echo "Only 4-GPU GLM FSDP is configured by this script; requested --gpus ${NUM_GPUS}" >&2
                exit 1
            fi ;;
        --dry-run) DRY_RUN=1 ;;
        *) echo "Unknown argument: $1"; exit 1 ;;
    esac
    shift
done

if [[ ! "${GPU_START}" =~ ^[0-9]+$ ]]; then
    echo "Invalid --gpu start id '${GPU_START}'" >&2
    exit 1
fi
GPU_IDS="${GPU_IDS//[[:space:]]/}"
[[ -n "${GPU_IDS}" ]] || GPU_IDS="$(make_gpu_ids "${GPU_START}" "${NUM_GPUS}")"
GPU_ID_COUNT="$(count_gpu_ids "${GPU_IDS}")"
if [[ "${GPU_ID_COUNT}" -ne "${NUM_GPUS}" ]]; then
    echo "GPU id list '${GPU_IDS}' contains ${GPU_ID_COUNT} ids, expected ${NUM_GPUS}" >&2
    exit 1
fi
GPU_IDS_LABEL="${GPU_IDS//,/-}"
RUN_LABEL="${NUM_GPUS}gpu${GPU_IDS_LABEL}_${BACKEND_LABEL}"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

log()   { echo -e "${BLUE}[$(date '+%H:%M:%S')]${NC} $*"; }
ok()    { echo -e "${GREEN}[$(date '+%H:%M:%S')] ✓${NC} $*"; }
warn()  { echo -e "${YELLOW}[$(date '+%H:%M:%S')] ⚠${NC}  $*"; }
error() { echo -e "${RED}[$(date '+%H:%M:%S')] ✗${NC} $*" >&2; }
run_timestamp() { date '+%Y%m%d_%H%M%S'; }
run_time_display() { date '+%Y-%m-%d %H:%M:%S %Z %z'; }
phase_banner() {
    echo ""
    echo -e "${BOLD}${CYAN}════════════════════════════════════════════════════════${NC}"
    echo -e "${BOLD}${CYAN}  $1${NC}"
    echo -e "${BOLD}${CYAN}════════════════════════════════════════════════════════${NC}"
    echo ""
}

check_env() {
    phase_banner "Environment Check"

    log "Python version: $(${PYTHON} --version 2>&1)"

    if ! command -v nvidia-smi &>/dev/null; then
        error "nvidia-smi not found, please verify CUDA driver is installed"
        exit 1
    fi

    local gpu_list actual_gpus
    gpu_list="$(nvidia-smi -L 2>/dev/null || true)"
    actual_gpus=$(printf '%s\n' "${gpu_list}" | sed '/^$/d' | wc -l)
    log "Detected GPUs: ${actual_gpus}"
    local gpu_id gpu_mem_mb gpu_mem_gb
    for gpu_id in ${GPU_IDS//,/ }; do
        if [[ ! "${gpu_id}" =~ ^[0-9]+$ ]]; then
            error "Invalid GPU id '${gpu_id}' in GPU_IDS='${GPU_IDS}'"
            exit 1
        fi
        if [[ "${actual_gpus}" -le "${gpu_id}" ]]; then
            error "Requested GPU ${gpu_id}, but only ${actual_gpus} GPU(s) detected"
            exit 1
        fi

        gpu_mem_mb=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits -i "${gpu_id}" 2>/dev/null | head -1 | tr -d ' ' || true)
        if [[ "${gpu_mem_mb}" =~ ^[0-9]+$ ]]; then
            gpu_mem_gb=$((gpu_mem_mb / 1024))
            log "Selected GPU: ${gpu_id}, VRAM: ${gpu_mem_gb} GiB"
            if [[ "${gpu_mem_gb}" -lt 20 ]]; then
                warn "GPU ${gpu_id} has less than 20 GiB VRAM; 4-GPU FSDP may still OOM"
            fi
        else
            warn "Could not parse GPU ${gpu_id} VRAM from nvidia-smi output: ${gpu_mem_mb:-<empty>}"
        fi
    done

    [[ -d "${MODEL_PATH}" ]] || { error "Model path not found: ${MODEL_PATH}"; exit 1; }
    ok "Model path: ${MODEL_PATH}"

    [[ -d "${LLAMA_FACTORY_DIR}" ]] || { error "LLaMA-Factory directory not found: ${LLAMA_FACTORY_DIR}"; exit 1; }
    ok "LLaMA-Factory: ${LLAMA_FACTORY_DIR}"

    if [[ ! -f "${DATA_DIR}/${DATASET_NAME}.json" ]]; then
        warn "Dataset not found: ${DATA_DIR}/${DATASET_NAME}.json"
        warn "Generating dataset automatically..."
        "${PYTHON}" "${GEN_DATASET_SCRIPT}" || {
            error "Dataset generation failed. Please run: python3 ${GEN_DATASET_SCRIPT}"
            exit 1
        }
    fi
    ok "Dataset: ${DATA_DIR}/${DATASET_NAME}.json"

    for cfg_file in "${TRAIN_CONFIG_BASE}" "${ACCEL_CONFIG}"; do
        [[ -f "${cfg_file}" ]] || { error "Required config not found: ${cfg_file}"; exit 1; }
    done
    ok "Training config: ${TRAIN_CONFIG_BASE}"
    ok "Accelerate config: ${ACCEL_CONFIG}"

    log "Python executable: ${PYTHON}"
    log "Conda env: ${CONDA_ENV}"
    log "CUDA_VISIBLE_DEVICES will be set to GPUs ${GPU_IDS}"
    log "FSDP processes: ${NUM_GPUS}; non-expert weights are sharded by accelerate FSDP"

    if ! "${PYTHON}" -c "import accelerate" &>/dev/null; then
        error "accelerate not installed in ${PYTHON}"
        exit 1
    fi
    ok "accelerate $(${PYTHON} -c 'import accelerate; print(accelerate.__version__)')"

    for pkg in psutil pynvml matplotlib pandas transformers; do
        if "${PYTHON}" -c "import ${pkg}" &>/dev/null; then
            ok "${pkg} installed"
        else
            warn "${pkg} not installed (some features limited)"
        fi
    done

    ok "Environment check passed"
}

setup_run_dir() {
    RUN_TS=$(run_timestamp)
    RUN_TIME="$(run_time_display)"
    RUN_TIMEZONE="$(date '+%Z %z')"
    RUN_LABEL="${NUM_GPUS}gpu${GPU_IDS_LABEL}_${BACKEND_LABEL}"
    LOG_DIR="${LOG_BASE}/${RUN_TS}_${RUN_LABEL}"
    mkdir -p "${LOG_DIR}/plots"
    log "Log directory: ${LOG_DIR}"

    [[ -p "${MONITOR_FIFO}" ]] && rm -f "${MONITOR_FIFO}"
    mkfifo "${MONITOR_FIFO}"

    export LOG_DIR RUN_TS RUN_TIME RUN_TIMEZONE RUN_LABEL MONITOR_FIFO
}

send_event() {
    local msg="$1"
    [[ "${DRY_RUN}" -eq 1 ]] && return
    if [[ -p "${MONITOR_FIFO}" ]]; then
        echo "${msg}" >> "${MONITOR_FIFO}" 2>/dev/null || true
    fi
}

start_monitor() {
    log "Starting system monitor process (process-tree root PID=$$)..."
    "${PYTHON}" "${MONITOR_SCRIPT}" \
        --out "${LOG_DIR}/monitor.csv" \
        --fifo "${MONITOR_FIFO}" \
        --interval 2 \
        --pid $$ \
        >> "${LOG_DIR}/monitor.log" 2>&1 &
    MONITOR_PID=$!
    log "Monitor PID: ${MONITOR_PID} (tracking script tree $$)"
    sleep 1
    send_event "pid:$$"
}

stop_monitor() {
    if [[ -n "${MONITOR_PID}" ]] && kill -0 "${MONITOR_PID}" 2>/dev/null; then
        log "Stopping monitor (PID: ${MONITOR_PID})..."
        kill -TERM "${MONITOR_PID}" || true
        wait "${MONITOR_PID}" 2>/dev/null || true
        MONITOR_PID=""
    fi
}

cleanup_model_output() {
    local phase_name="$1"
    local model_dir="${LOG_DIR}/${phase_name}/model_output"
    if [[ "${KEEP_MODEL_OUTPUT}" -eq 1 ]]; then
        log "[cleanup] KEEP_MODEL_OUTPUT=1, keeping ${model_dir}"
        return
    fi
    if [[ -d "${model_dir}" ]]; then
        log "[cleanup] Removing ${model_dir} to free disk space..."
        rm -rf "${model_dir}"
        ok "[cleanup] ${phase_name}/model_output deleted"
    fi
}

make_phase_config() {
    local phase_name="$1"; shift
    local phase_dir="${LOG_DIR}/${phase_name}"
    mkdir -p "${phase_dir}"
    local cfg="${phase_dir}/train_config.yaml"

    cp "${TRAIN_CONFIG_BASE}" "${cfg}"
    sed -i "s|output_dir: .*|output_dir: ${phase_dir}/model_output|g" "${cfg}"
    sed -i "s|overwrite_output_dir: .*|overwrite_output_dir: true|g" "${cfg}"

    while [[ $# -gt 0 ]]; do
        local kv="$1"; shift
        local key="${kv%%=*}"
        local val="${kv#*=}"
        if grep -q "^${key}:" "${cfg}"; then
            sed -i "s|^${key}: .*|${key}: ${val}|g" "${cfg}"
        else
            echo "${key}: ${val}" >> "${cfg}"
        fi
    done

    echo "${cfg}"
}

run_train() {
    local phase_name="$1"
    local desc="$2"
    local train_cfg="$3"
    local phase_log="${LOG_DIR}/${phase_name}/train.log"
    local exit_code=0

    log "Starting training [${phase_name}]: ${desc}"
    log "  accelerate config : $(basename "${ACCEL_CONFIG}")"
    log "  GPUs              : ${GPU_IDS}"
    log "  FSDP processes    : ${NUM_GPUS}"
    send_event "phase:${phase_name}"
    send_event "event:train_start"

    local accelerate_bin="${CONDA_BIN_DIR}/accelerate"
    [[ ! -x "${accelerate_bin}" ]] && accelerate_bin="accelerate"

    local cmd=(
        env
        USE_KT=1
        ACCELERATE_USE_KT=true
        ACCELERATE_KT_TRAIN_MODE=full
        ACCELERATE_KT_MODEL_MAX_LENGTH="${CUTOFF_LEN}"
        CUDA_VISIBLE_DEVICES="${GPU_IDS}"
        "${accelerate_bin}" launch
        --config_file "${ACCEL_CONFIG}"
        -m llamafactory.cli train
        "${train_cfg}"
    )

    if [[ "${DRY_RUN}" -eq 1 ]]; then
        log "[DRY-RUN] Command: ${cmd[*]}"
        return 0
    fi

    pushd "${LLAMA_FACTORY_DIR}" > /dev/null
    set +e
    "${cmd[@]}" 2>&1 | tee "${phase_log}"
    exit_code=${PIPESTATUS[0]}
    set -e
    popd > /dev/null

    send_event "event:train_end"
    return "${exit_code}"
}

generate_static_memory_breakdown() {
    phase_banner "Phase 0a: Static Memory Attribution Estimate"

    "${PYTHON}" - "${MODEL_PATH}" "${CUTOFF_LEN}" "${NUM_GPUS}" <<'PYEOF' | tee "${LOG_DIR}/memory_breakdown_estimate.txt"
import json
import os
import sys
from pathlib import Path

model_path = Path(sys.argv[1])
cutoff_len = int(sys.argv[2])
num_gpus = int(sys.argv[3])

def gb(n):
    return n / 1e9

def gib(n):
    return n / (1024 ** 3)

cfg = json.loads((model_path / "config.json").read_text())
cache_path = model_path / ".moe_analysis_cache.json"
cache = {}
if cache_path.exists():
    try:
        cache = json.loads(cache_path.read_text()).get("result", {})
    except Exception:
        cache = {}

H = int(cfg["hidden_size"])
moe_I = int(cfg["moe_intermediate_size"])
dense_I = int(cfg.get("intermediate_size", 0) or 0)
E = int(cfg["n_routed_experts"])
top_k = int(cfg["num_experts_per_tok"])
layers = int(cfg["num_hidden_layers"])
dense_first = int(cfg.get("first_k_dense_replace", 0) or 0)
moe_layers = max(layers - dense_first, 0)
vocab = int(cfg["vocab_size"])
heads = int(cfg["num_attention_heads"])
kv_heads = int(cfg["num_key_value_heads"])
head_dim = int(cfg["head_dim"])

expert_params = E * 3 * H * moe_I * moe_layers
expert_bf16 = expert_params * 2
expert_grad_fp32 = expert_params * 4
expert_adam_fp32 = expert_params * 8
expert_train_fp32_total = expert_bf16 + expert_grad_fp32 + expert_adam_fp32

expert_grad_bf16 = expert_params * 2
expert_adam_bf16 = expert_params * 4
expert_train_bf16_state_total = expert_bf16 + expert_grad_bf16 + expert_adam_bf16

rest_gib = float(cache.get("rest_size_gb", 0.0) or 0.0)
expert_cache_gib = float(cache.get("all_experts_size_gb", 0.0) or 0.0)
total_cache_gib = float(cache.get("total_size_gb", 0.0) or 0.0)
disk_bytes = 0
for p in model_path.glob("model-*.safetensors"):
    try:
        disk_bytes += p.stat().st_size
    except OSError:
        pass

gpu_param_gib = rest_gib if rest_gib > 0 else gib((vocab * H * 2) + (layers * 4 * H * H * 2))
gpu_grad_bf16_gib = gpu_param_gib
gpu_adam_bf16_gib = gpu_param_gib * 2
activation_gib = 8.0
shard_divisor = max(num_gpus, 1)
gpu_param_shard_gib = gpu_param_gib / shard_divisor
gpu_grad_bf16_shard_gib = gpu_grad_bf16_gib / shard_divisor
gpu_adam_bf16_shard_gib = gpu_adam_bf16_gib / shard_divisor
gpu_peak_bf16_state = gpu_param_shard_gib + gpu_grad_bf16_shard_gib + gpu_adam_bf16_shard_gib + activation_gib

gpu_grad_fp32_gib = gpu_param_gib * 2
gpu_adam_fp32_gib = gpu_param_gib * 4
gpu_grad_fp32_shard_gib = gpu_grad_fp32_gib / shard_divisor
gpu_adam_fp32_shard_gib = gpu_adam_fp32_gib / shard_divisor
gpu_peak_fp32_state = gpu_param_shard_gib + gpu_grad_fp32_shard_gib + gpu_adam_fp32_shard_gib + activation_gib

print("=" * 72)
print("GLM-4.5-Air full-FT memory attribution estimate")
print("=" * 72)
print(f"model_path              : {model_path}")
print(f"architecture            : {cfg.get('architectures', ['?'])[0]}")
print(f"model_type              : {cfg.get('model_type')}")
print(f"layers                  : {layers} total, first {dense_first} dense, {moe_layers} routed-MoE layers")
print(f"hidden / dense-I / moe-I: H={H}, dense_I={dense_I}, moe_I={moe_I}")
print(f"attention               : heads={heads}, kv_heads={kv_heads}, head_dim={head_dim}")
print(f"experts                 : routed={E}, active_per_token={top_k}")
print(f"cutoff_len              : {cutoff_len}")
print(f"FSDP GPU processes      : {num_gpus}")
print()
print("Source size sanity")
print(f"  safetensors disk bytes                 : {gb(disk_bytes):8.1f} GB ({gib(disk_bytes):.1f} GiB)")
if cache:
    print(f"  KTransformers cache all_experts_size   : {expert_cache_gib:8.1f} GiB")
    print(f"  KTransformers cache rest_size          : {rest_gib:8.1f} GiB")
    print(f"  KTransformers cache total_size         : {total_cache_gib:8.1f} GiB")
print()
print("CPU-side routed expert training footprint")
print(f"  Expert params                           : {expert_params/1e9:8.1f} B params")
print(f"  Expert BF16 weights                     : {gb(expert_bf16):8.1f} GB ({gib(expert_bf16):.1f} GiB)")
print(f"  Expert gradients, if FP32               : {gb(expert_grad_fp32):8.1f} GB ({gib(expert_grad_fp32):.1f} GiB)")
print(f"  Expert AdamW states m+v, if FP32        : {gb(expert_adam_fp32):8.1f} GB ({gib(expert_adam_fp32):.1f} GiB)")
print(f"  Expert subtotal, FP32 grad/Adam         : {gb(expert_train_fp32_total):8.1f} GB ({gib(expert_train_fp32_total):.1f} GiB)")
print(f"  Expert subtotal, BF16-like grad/states  : {gb(expert_train_bf16_state_total):8.1f} GB ({gib(expert_train_bf16_state_total):.1f} GiB)")
print("  Note: exact grad/optimizer dtype is implementation-dependent; runtime monitor is authoritative.")
print()
print("GPU-side non-expert / dense-state estimate, per FSDP rank")
print(f"  Non-expert BF16 params from KT cache     : {gpu_param_gib:8.1f} GiB total")
print(f"  FSDP-sharded non-expert params/rank      : {gpu_param_shard_gib:8.1f} GiB")
print(f"  + sharded gradients + AdamW, BF16-like   : {gpu_grad_bf16_shard_gib + gpu_adam_bf16_shard_gib:8.1f} GiB")
print(f"  + activation/workspace allowance/rank    : {activation_gib:8.1f} GiB")
print(f"  Estimated GPU peak/rank, BF16-like states: {gpu_peak_bf16_state:8.1f} GiB / 24 GiB")
print(f"  Estimated GPU peak/rank, FP32 states     : {gpu_peak_fp32_state:8.1f} GiB / 24 GiB")
if gpu_peak_bf16_state > 24:
    print("  WARNING: BF16-like per-rank estimate exceeds 24 GiB; OOM is plausible.")
print()
print("Attribution guide for observed monitor peaks")
print("  GPU VRAM peak usually includes non-expert params, activations, gradients, optimizer states, CUDA workspaces.")
print("  CPU RAM peak usually includes BF16 expert weights, expert gradients, AdamW m/v states, NUMA work buffers, dataloader/tokenizer caches.")
print("  Optimizer memory becomes visible after the first optimizer step, not necessarily during model load.")
PYEOF
}

analyze_log() {
    local phase_name="$1"
    local log_file="${LOG_DIR}/${phase_name}/train.log"
    local result_file="${LOG_DIR}/${phase_name}/log_analysis.txt"

    [[ ! -f "${log_file}" ]] && return

    {
        echo "=== Phase: ${phase_name} Log Analysis ==="
        echo "--- Training Loss (last 20 entries) ---"
        grep -i "loss" "${log_file}" | tail -20 || echo "(no loss records found)"

        echo ""
        echo "--- Gradient Norm (last 30 records) ---"
        grep -i "grad_norm\|gradient_norm" "${log_file}" | tail -30 || echo "(no grad_norm records)"

        echo ""
        echo "--- Optimizer / trainable parameter records ---"
        grep -i "optimizer\|adamw\|trainable params\|trainable parameters\|kt_train_mode\|full_weight" \
             "${log_file}" 2>/dev/null | tail -40 || echo "(no optimizer records found)"

        echo ""
        echo "--- NaN / Inf occurrence count ---"
        local nan_count inf_count
        nan_count=$(grep -ci "nan" "${log_file}" 2>/dev/null || echo 0)
        inf_count=$(grep -ci "inf" "${log_file}" 2>/dev/null || echo 0)
        echo "NaN lines: ${nan_count}; Inf lines: ${inf_count}"

        echo ""
        echo "--- KT-related warnings/errors ---"
        grep -i "ktransformer\|kt_kernel\|amx\|moe\|expert\|backward\|optimizer\|memory" \
             "${log_file}" 2>/dev/null | grep -i "warn\|error\|fail\|oom\|out of memory" | tail -40 \
             || echo "(no KT-related alerts)"

        echo ""
        echo "--- Exit symptoms ---"
        if grep -qi "segmentation fault\|sigsegv\|core dumped" "${log_file}"; then
            echo "SIGSEGV / core dump detected"
        fi
        if grep -qi "cuda out of memory\|out of memory\|oom" "${log_file}"; then
            echo "CUDA or host OOM detected"
        fi
        if grep -qi "ddp_timeout\|timeout expired" "${log_file}"; then
            echo "DDP timeout detected"
        fi
    } | tee "${result_file}"
}

run_phase4() {
    phase_banner "Phase 4: Stability Extension + TPS Benchmark (${PHASE4_STEPS} steps)"
    local cfg
    cfg=$(make_phase_config "phase4" \
        "max_steps=${PHASE4_STEPS}" \
        "gradient_accumulation_steps=1" \
        "save_strategy='no'" \
        "logging_steps=1")

    log "Steps: ${PHASE4_STEPS} | GPUs: ${GPU_IDS} | cutoff_len: ${CUTOFF_LEN}"
    log "TPS measurement: skip first ${WARMUP_SKIP} warm-up steps"

    local t_start
    t_start=$(date +%s)
    local exit_code=0
    run_train "phase4" "stability + TPS benchmark (${PHASE4_STEPS} steps)" "${cfg}" || exit_code=$?
    local t_end
    t_end=$(date +%s)
    local total_sec=$((t_end - t_start))

    {
        echo "=== Phase 4 Performance Analysis ==="
        echo "Total wall time: ${total_sec} seconds"
        echo "Expected steps: ${PHASE4_STEPS}"
        echo ""
        echo "--- Accurate TPS (warmup excluded) ---"
        "${PYTHON}" - "${LOG_DIR}/phase4/train.log" "${CUTOFF_LEN}" "${NUM_GPUS}" "${WARMUP_SKIP}" <<'PYEOF'
import re
import statistics
import sys

log_path = sys.argv[1]
cutoff_len = int(sys.argv[2])
num_gpus = int(sys.argv[3])
warmup_n = int(sys.argv[4])

try:
    text = open(log_path, errors="replace").read()
except FileNotFoundError:
    print("  train.log not found")
    sys.exit(0)

pattern = re.compile(r'(\d+)/\d+\s+\[[\d:]+<[\d:]+,\s*([\d.]+)\s*s/it\]')
seen = {}
for m in pattern.finditer(text):
    seen[int(m.group(1))] = float(m.group(2))
steps = sorted(seen.items())
stable = [(s, t) for s, t in steps if s > warmup_n]
tokens_per_step = num_gpus * cutoff_len

print(f"  total_steps_logged : {len(steps)}")
print(f"  warmup_steps_skip  : {warmup_n}")
print(f"  stable_steps       : {len(stable)}")
print(f"  tokens_per_step    : {tokens_per_step}")
if not stable:
    print("  not enough steps to compute stable TPS")
    sys.exit(0)

times = [t for _, t in stable]
avg_t = sum(times) / len(times)
med_t = statistics.median(times)
min_t = min(times)
max_t = max(times)

print(f"  step_time_avg      : {avg_t:.2f} s")
print(f"  step_time_median   : {med_t:.2f} s")
print(f"  step_time_min      : {min_t:.2f} s")
print(f"  step_time_max      : {max_t:.2f} s")
print(f"  TPS (avg)          : {tokens_per_step / avg_t:.2f} tokens/sec")
print(f"  TPS (median)       : {tokens_per_step / med_t:.2f} tokens/sec")
print(f"  TPS (peak)         : {tokens_per_step / min_t:.2f} tokens/sec")
PYEOF
        echo ""
        echo "--- Router / MoE auxiliary loss records ---"
        grep -i "aux_loss\|router_loss\|balance_loss" "${LOG_DIR}/phase4/train.log" 2>/dev/null | tail -10 \
            || echo "(no router aux loss found)"
        echo ""
        echo "--- Optimizer / memory-related records ---"
        grep -i "optimizer\|adamw\|memory\|alloc\|cuda\|kt" "${LOG_DIR}/phase4/train.log" 2>/dev/null | tail -50 \
            || echo "(no optimizer/memory records found)"
    } | tee "${LOG_DIR}/phase4_analysis.txt"

    analyze_log "phase4"
    echo "${exit_code}" > "${LOG_DIR}/phase4/exit_code.txt"
    cleanup_model_output "phase4"
    return "${exit_code}"
}

summarize_observed_memory() {
    phase_banner "Observed Runtime Memory Breakdown"

    "${PYTHON}" - "${LOG_DIR}/monitor.csv" <<'PYEOF' | tee "${LOG_DIR}/observed_memory_breakdown.txt"
import csv
import sys
from collections import defaultdict
from pathlib import Path

path = Path(sys.argv[1])
if not path.exists():
    print("monitor.csv not found")
    sys.exit(0)

rows = list(csv.DictReader(path.open()))
if not rows:
    print("monitor.csv is empty")
    sys.exit(0)

def f(row, key):
    try:
        return float(row.get(key, 0) or 0)
    except Exception:
        return 0.0

gpu_cols = sorted(
    [k for k in rows[0] if k.startswith("gpu") and k.endswith("_mem_used_mb") and not k.startswith("proc_")],
    key=lambda x: int(x.split("_")[0][3:]),
)
has_proc_ram = "proc_ram_gb" in rows[0]
use_proc_gpu = all(f"proc_gpu{c.split('_')[0][3:]}_mem_mb" in rows[0] for c in gpu_cols) if gpu_cols else False

def measured_ram(row):
    if has_proc_ram:
        return f(row, "proc_ram_gb")
    return f(row, "ram_used_gb")

def measured_gpu_gb(row, host_col):
    if use_proc_gpu:
        return f(row, f"proc_gpu{host_col.split('_')[0][3:]}_mem_mb") / 1024
    return f(row, host_col) / 1024

baseline_ram = measured_ram(rows[0])
baseline_gpu = {c: measured_gpu_gb(rows[0], c) for c in gpu_cols}

phase_stats = defaultdict(lambda: {"ram": 0.0, "gpu": defaultdict(float)})
overall = {"ram": 0.0, "gpu": defaultdict(float)}

for row in rows:
    phase = row.get("phase") or "unknown"
    ram = measured_ram(row)
    phase_stats[phase]["ram"] = max(phase_stats[phase]["ram"], ram)
    overall["ram"] = max(overall["ram"], ram)
    for c in gpu_cols:
        val = measured_gpu_gb(row, c)
        phase_stats[phase]["gpu"][c] = max(phase_stats[phase]["gpu"][c], val)
        overall["gpu"][c] = max(overall["gpu"][c], val)

scope = "process_tree" if (has_proc_ram or use_proc_gpu) else "host"
print(f"=== Observed Runtime Peaks from monitor.csv ({scope}) ===")
print(f"baseline_ram_gb       : {baseline_ram:.2f}")
print(f"peak_ram_gb           : {overall['ram']:.2f}")
print(f"peak_ram_delta_gb     : {overall['ram'] - baseline_ram:.2f}")
for c in gpu_cols:
    print(f"baseline_{c[:-12]}_gb  : {baseline_gpu[c]:.2f}")
    print(f"peak_{c[:-12]}_gb      : {overall['gpu'][c]:.2f}")
    print(f"peak_{c[:-12]}_delta_gb: {overall['gpu'][c] - baseline_gpu[c]:.2f}")

print()
print("=== Peaks by Phase ===")
for phase in sorted(phase_stats):
    st = phase_stats[phase]
    print(f"[{phase}]")
    print(f"  ram_peak_gb: {st['ram']:.2f}  delta_from_start: {st['ram'] - baseline_ram:.2f}")
    for c in gpu_cols:
        print(f"  {c[:-12]}_peak_gb: {st['gpu'][c]:.2f}  delta_from_start: {st['gpu'][c] - baseline_gpu[c]:.2f}")

print()
print("=== Attribution Notes ===")
print("GPU delta after model load is mostly non-expert BF16 params and CUDA workspaces.")
print("GPU delta after first backward adds activations and gradients.")
print("GPU delta after first optimizer step adds optimizer states if they are GPU-resident.")
print("CPU delta after model load is mostly AMXBF16 routed expert weights and KT NUMA buffers.")
print("CPU delta after backward/optimizer adds expert gradients and AdamW m/v states if KT stores them in host RAM.")
PYEOF
}

generate_summary() {
    phase_banner "Generating Summary Report"
    local summary="${LOG_DIR}/SUMMARY.md"
    {
        echo "# GLM-4.5-Air Full-FT Test Summary"
        echo ""
        echo "**Test time**: ${RUN_TIME}"
        echo "**Run label**: ${RUN_LABEL}"
        echo "**Log directory**: ${LOG_DIR}"
        echo "**GPUs**: CUDA devices ${GPU_IDS} (${NUM_GPUS} FSDP processes)"
        echo "**Accelerate config**: $(basename "${ACCEL_CONFIG}")"
        echo "**Model**: ${MODEL_PATH}"
        echo "**Dataset**: ${DATASET_NAME} @ ${DATA_DIR}"
        echo "**cutoff_len**: ${CUTOFF_LEN}"
        echo "**warmup_skip**: ${WARMUP_SKIP}"
        echo ""
        echo "## Phase Exit Codes"
        echo ""
        echo "| Phase | Exit Code | Status |"
        echo "|-------|-----------|--------|"
        local ec_file="${LOG_DIR}/phase4/exit_code.txt"
        if [[ -f "${ec_file}" ]]; then
            local ec
            ec=$(cat "${ec_file}")
            local status="Pass"
            [[ "${ec}" -ne 0 ]] && status="Fail(${ec})"
            echo "| phase4 | ${ec} | ${status} |"
        else
            echo "| phase4 | - | Skipped |"
        fi
        echo ""
        echo "## TPS Summary"
        echo ""
        if [[ -f "${LOG_DIR}/phase4_analysis.txt" ]]; then
            grep -E "TPS|tokens_per_step|stable_steps|step_time" "${LOG_DIR}/phase4_analysis.txt" 2>/dev/null \
                | sed 's/^/  /' || echo "  (run Phase 4 to get TPS data)"
        else
            echo "  (Phase 4 not run)"
        fi
        echo ""
        echo "## Memory Summary"
        echo ""
        if [[ -f "${LOG_DIR}/observed_memory_breakdown.txt" ]]; then
            grep -E "peak_ram|peak_gpu|baseline_ram" "${LOG_DIR}/observed_memory_breakdown.txt" 2>/dev/null \
                | head -20 | sed 's/^/  /' || echo "  (monitor data unavailable)"
        else
            echo "  (monitor data unavailable)"
        fi
        echo ""
        echo "## Key Files"
        echo ""
        echo "- Static estimate: ${LOG_DIR}/memory_breakdown_estimate.txt"
        echo "- Observed memory: ${LOG_DIR}/observed_memory_breakdown.txt"
        echo "- TPS analysis: ${LOG_DIR}/phase4_analysis.txt"
        echo "- Monitor CSV: ${LOG_DIR}/monitor.csv"
        echo "- Plots: ${LOG_DIR}/plots/"
        echo ""
        echo "## Unclear / Assumed Training Parameters"
        echo ""
        echo "- learning_rate=1e-5, cosine schedule and warmup_ratio=0.1 follow the Qwen full-FT stress baseline, not a GLM-tuned recipe."
        echo "- optim=adamw_torch is set explicitly so optimizer memory is attributable to AdamW m/v states."
        echo "- batch size is fixed at 1 and Phase 4 uses gradient_accumulation_steps=1 for TPS."
        echo "- save_strategy='no' is injected per phase, but model_output is still cleaned unless KEEP_MODEL_OUTPUT=1."
    } > "${summary}"
    log "Summary: ${summary}"
    cat "${summary}"
}

cleanup() {
    stop_monitor
    [[ -p "${MONITOR_FIFO}" ]] && rm -f "${MONITOR_FIFO}"
}

trap cleanup EXIT INT TERM

main() {
    echo ""
    echo -e "${BOLD}GLM-4.5-Air KTransformers REAL Full Fine-Tuning Test Suite (AMXBF16)${NC}"
    echo -e "Time: $(run_time_display)"
    echo -e "Run label: ${RUN_LABEL}"
    echo -e "KT train mode: ${ACCELERATE_KT_TRAIN_MODE}"
    echo -e "Model: ${MODEL_PATH}"
    echo -e "Dataset: ${DATASET_NAME} @ ${DATA_DIR}"
    echo -e "GPUs: ${GPU_IDS} | FSDP processes: ${NUM_GPUS} | cutoff_len: ${CUTOFF_LEN} | warmup_skip: ${WARMUP_SKIP}"
    echo ""

    check_env
    setup_run_dir
    generate_static_memory_breakdown

    if [[ "${DRY_RUN}" -eq 0 ]]; then
        start_monitor
    fi

    local overall_exit=0

    if [[ "${SKIP_PHASE4}" -eq 0 ]]; then
        run_phase4 || overall_exit=1
    else
        log "Phase 4 skipped"
    fi

    stop_monitor
    summarize_observed_memory
    generate_summary

    if [[ -f "${ANALYZE_SCRIPT}" && "${DRY_RUN}" -eq 0 ]]; then
        log "Running visualization analysis..."
        "${PYTHON}" "${ANALYZE_SCRIPT}" --log-dir "${LOG_DIR}" \
            >> "${LOG_DIR}/analyze.log" 2>&1 && \
            ok "Charts generated: ${LOG_DIR}/plots/" || \
            warn "analyze.py failed, run manually: python3 ${ANALYZE_SCRIPT} --log-dir ${LOG_DIR}"
    fi

    if [[ "${overall_exit}" -eq 0 ]]; then
        ok "Completed — log directory: ${LOG_DIR}"
    else
        warn "Some phases failed — check: ${LOG_DIR}/SUMMARY.md"
    fi
    return "${overall_exit}"
}

main "$@"
